apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia
  labels:
    app: conversao-distancia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: rafallltm/conversao-distancia:v2
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"  #milicores, ou seja, 1/4 de um núcleo
          limits:
            memory: "128Mi"
            cpu: "500m"  #milicores, ou seja, 1/2 de um núcleo
        
---

apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
  labels:
    app: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer